FROM node:20-alpine

# 更新系統包以解決已知漏洞
RUN apk update && apk upgrade && apk add --no-cache openssl

WORKDIR /app
COPY package*.json ./

# 添加依賴項之前先安裝
RUN npm config set registry https://registry.npmjs.org/
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "start"]