version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.stage
    container_name: backend-stage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - PORT=3000
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.stage
    container_name: frontend-stage
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=staging
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge