version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.stage
    container_name: backend-stage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - PORT=3000
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.stage
    container_name: frontend-stage
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=staging
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL 服務 (生產環境)
  postgres:
    image: postgres:15-alpine
    container_name: postgres-prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    
  # Redis 服務 (生產環境)
  redis:
    image: redis:7-alpine
    container_name: redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
  
networks:
  app-network:
    driver: bridge